### ISSUE TITLE
Any plans to update scripts to support ubuntu22.04 and cuda 11.8

### ISSUE THREAD

**Issue by saket424** [NVIDIA-AI-IOT/deepstream_dockers#2]
ubuntu20.04 ==> nv-tensorrt-repo-ubuntu2004-cuda11.6-trt8.4.1.5-ga-20220604_1-1_amd64.deb
ubuntu22.04 ==> nv-tensorrt-local-repo-ubuntu2204-8.5.2-cuda-11.8_1.0-1_amd64.deb

**Comment by nv-ad** [comment]
DS 6.4 supports Ubuntu 22.04 and CUDA 12.2
